[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

[[redirects]]
  from = "/demo-form.html"
  to = "/demo-form.html"
  status = 200

[[redirects]]
  from = "/nmms-form.html"
  to = "/nmms-form.html"
  status = 200

[[redirects]]
  from = "/pmrf-form.html"
  to = "/pmrf-form.html"
  status = 200

[[redirects]]
  from = "/extension-demo.html"
  to = "/extension-demo.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"